// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5UQfA9vNu4CA4bWD6DXD3BSFxSQRknE',
    appId: '1:1068928675747:web:c3932e7d2035f79c5eb416',
    messagingSenderId: '1068928675747',
    projectId: 'taskify-d4dec',
    authDomain: 'taskify-d4dec.firebaseapp.com',
    storageBucket: 'taskify-d4dec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2AC8pFnk3B_4XRHGLOALOyGO9ZswxClg',
    appId: '1:1068928675747:android:2d2832f0038aa1435eb416',
    messagingSenderId: '1068928675747',
    projectId: 'taskify-d4dec',
    storageBucket: 'taskify-d4dec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7dULznzpxCasLu_6cj-62k2DU0UnFq-U',
    appId: '1:1068928675747:ios:ab0f5473144bce5d5eb416',
    messagingSenderId: '1068928675747',
    projectId: 'taskify-d4dec',
    storageBucket: 'taskify-d4dec.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7dULznzpxCasLu_6cj-62k2DU0UnFq-U',
    appId: '1:1068928675747:ios:ab0f5473144bce5d5eb416',
    messagingSenderId: '1068928675747',
    projectId: 'taskify-d4dec',
    storageBucket: 'taskify-d4dec.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );
}
