// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:taskify/src/features/auth/data/models/user_model.dart';
import 'package:taskify/src/features/boards/data/models/board_model.dart';
import 'package:taskify/src/features/boards/data/models/task_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BoardModelAdapter());
    registerAdapter(TaskModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BoardModelAdapter());
    registerAdapter(TaskModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
